using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.IdentityModel.Tokens.Jwt;
using Metis.Models.Store;
using Metis.Models.Requests;
using Metis.Models.Managers;
using Metis.Models;
using Microsoft.IdentityModel.Tokens;
using System.Security.Claims;
using System.Globalization;
using System.Text;

namespace Metis.API.Controllers
{
    //[Authorize]
    [ApiController]
    [Route("[controller]")]
    public class UserController : BaseController
    {
        private readonly SignInManager<User> _signInManager;
        private readonly IConfiguration _configuration;

        public UserController(ApplicationDbContext dataContext, UserManager<User> userManager, RoleManager<Role> roleManager, SignInManager<User> signInManager, IConfiguration configuration)
            : base(dataContext, userManager, roleManager)
        {
            _signInManager = signInManager;
            _configuration = configuration;
        }

        // [HttpGet]
        // [AllowAnonymous]
        // public async Task<IActionResult> Login(string returnUrl = null)
        // {
        //     // Clear the existing external cookie to ensure a clean login process
        //     await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
        //     ViewData["ReturnUrl"] = returnUrl;
        //     return Ok();
        // }

        [HttpPost]
        [Route("LoginUser")]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginRequest model)
        {
            var user = _userManager.FindByEmailAsync(model.Email).Result;
            // if (!user.IsActive)
            // {
            //     return NotFound();
            // }
            var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, false, false);
            if (result.Succeeded)
            {
                var tokenHandler = new JwtSecurityTokenHandler();
                ClaimsIdentity Subject = new ClaimsIdentity(new Claim[]  
                {  
                    new Claim("UserId", user.Id.ToString()),  
                    new Claim("FirstName", user.FirstName),  
                    new Claim("LastName",user.LastName),  
                    new Claim("EmailId",user.Email == null ? "" : user.Email),  
                    new Claim("UserName",user.UserName == null ? "" : user.UserName),  
                    new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),  
                });  
                IEnumerable<Role> roles = RoleManager.GetRolesByUserId(_dataContext, user.Id);
                foreach (var item in roles)  
                {  
                    Subject.AddClaim(new Claim(ClaimTypes.Role, item.Name));
                }  
                var key = Encoding.ASCII.GetBytes(_configuration["jwt:Secret"]);
                var tokenLifetime = TimeSpan.FromSeconds(Double.Parse(_configuration["jwt:TokenLifetime"]));
                var tokenDescriptor = new SecurityTokenDescriptor
                {
                    Subject = Subject,
                    Expires = DateTime.UtcNow.Add(tokenLifetime),
                    SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
                };
                var tokenDescription = tokenHandler.CreateToken(tokenDescriptor);
                var token = tokenHandler.WriteToken(tokenDescription); 
                return Ok(token);
            }
            else
            {
                return NotFound();
            }  
        }

        // [HttpGet]
        // public async Task<IActionResult> LogOut()
        // {
        //     await _signInManager.SignOutAsync();
        //     return RedirectToAction(nameof(HomeController.Index), "Home");
        // }


        [HttpPost]
        [Route("AddUser")]
        // [Authorize(Roles = "Country Admin,Administrator")]
        // [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserAsync(AddUserRequest model)
        {
            int numberOfNonAlphanumericCharacters = new Random().Next(1, _userManager.Options.Password.RequiredLength - 1);
            int passwordlength = int.Parse(_configuration["Identity:AutoGeneratedPasswordLength"]);
            string password = Password.Generate(passwordlength, numberOfNonAlphanumericCharacters);

            IdentityResult result = await UserManager.AddUser(_userManager, model.FirstName, model.LastName, model.Email, password);
            if (!result.Succeeded)
            {
                var error = string.Join(",", result.Errors.Select(e => e.Description));
                throw new Exception(error);
            }
            result = await UserManager.AddUserToRole(_userManager, model.Email, model.Role);
            if (!result.Succeeded)
            {
                var error = string.Join(",", result.Errors.Select(e => e.Description));
                throw new Exception(error);
            }

            // var smptServer = _configuration["Email:SmptServer"];
            // var smptPort = int.Parse(_configuration["Email:SmptPort"]);
            // var enableSsl = bool.Parse(_configuration["Email:EnableSsl"]);
            // var smptUsername = _configuration["Email:SmptUsername"];
            // var smptPassword = _configuration["Email:SmptPassword"];
            // var sender = _configuration["Email:Sender"];
            // Email email = new Email(smptServer, smptPort, enableSsl, smptUsername, smptPassword, sender);
            // var filePath = Path.Combine(Directory.GetCurrentDirectory(), "Templates", "email.html");
            // string message = System.IO.File.ReadAllText(filePath);
            // message = message.Replace("{{TEMPORARYPASSWORD}}", password);
            // email.Send(new string[] { model.Email }, message, "Temporary password", true, System.Net.Mail.MailPriority.High);

            return Ok();
        }

        [HttpGet]
        [Route("GetCurrentUsers")]
        [Authorize]
        public async Task<IActionResult> GetCurrentUsersAsync()
        {
            var data = await _userManager.GetUserAsync(HttpContext.User);
            return Ok(data);
        }

        [HttpGet]
        [Route("GetUsers")]
        [Authorize(Roles = "Country Admin,Administrator")]
        public async Task<IActionResult> GetUsersAsync()
        {
            await IsUserValidAsync(new string[] { "Country Admin", "Administrator" });
            IEnumerable<User> users = UserManager.GetUsers(_userManager);
            return Ok(users);
        }

        [HttpGet]
        [Route("GetUserById")]
        // [Authorize(Roles = "Country Admin,Administrator")]
        public async Task<IActionResult> GetUserByIdAsync(int id)
        {
            User users = await UserManager.GetUserById(_userManager, id);
            return Ok(users);
        }

        [AllowAnonymous]
        [HttpGet]
        [Route("GetUsersByPage")]
        public async Task<IActionResult> GetUsersByPageAsync(int page, int itemsPerPage)
        {
            IEnumerable<User> users = await UserManager.GetUsersByPage(_dataContext, page, itemsPerPage);
            return Ok(users);
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        [Route("GetUsersByPageAndSearchQuery")]
        public async Task<IActionResult> GetUsersByPageAndSearchQueryAsync(int page, int itemsPerPage, string searchQuery)
        {
            IEnumerable<User> users = await UserManager.GetUsersByPageAndSearchQuery(_dataContext, page, itemsPerPage, searchQuery);
            return Ok(users);
        }

        [HttpGet]
        [Route("GetUsersCount")]
        // [Authorize(Roles = "Country Admin,Administrator")]
        public async Task<IActionResult> GetUsersCountAsync()
        {
            int counter = await UserManager.GetUsersCount(_userManager);
            return Ok(counter);
        }

        [HttpGet]
        [Route("GetUsersBySearchQueryCount")]
        // [Authorize(Roles = "Country Admin,Administrator")]
        public async Task<IActionResult> GetUsersBySearchQueryCountAsync(string searchQuery)
        {
            int counter = await UserManager.GetUsersBySearchQueryCount(_userManager, searchQuery);
            return Ok(counter);
        }

        [HttpPost]
        [Route("EditUser")]
        // [Authorize(Roles = "Country Admin,Administrator")]
        // [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUserAsync(EditUserRequest model)
        {
            var result = await UserManager.EditUser(_userManager, model.Id, model.FirstName, model.LastName, model.Email);

            // var roles = RoleManager.GetRolesByUserId(_dataContext, model.Id).Select(r => r.Name);
            // foreach (var role in roles)
            // {
            //     result = await UserManager.RemoveUserFromRole(_userManager, model.Email, role);
            //     if (!result.Succeeded)
            //     {
            //         var error = string.Join(",", result.Errors.Select(e => e.Description));
            //         throw new Exception(error);
            //     }
            // }

            // result = await UserManager.AddUserToRole(_userManager, model.Email, model.Role);
            // if (!result.Succeeded)
            // {
            //     var error = string.Join(",", result.Errors.Select(e => e.Description));
            //     throw new Exception(error);
            // }
            return Ok();
        }

        [HttpPost]
        [Route("DeleteUsers")]
        [Authorize(Roles = "Country Admin,Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUsersAsync(DeleteUsersRequest model)
        {
            IdentityResult result = null;
            for (int i = 0; i < model.Emails.Count(); i++)
            {
                result = await UserManager.DeleteUser(_userManager, model.Emails[i]);
                if (!result.Succeeded)
                {
                    var error = string.Join(",", result.Errors.Select(e => e.Description));
                    throw new Exception(error);
                }
            }
            return Ok();
        }

        [HttpDelete]
        [Route("DeleteUserById")]
        // [Authorize(Roles = "Country Admin,Administrator")]
        // [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUserByIdAsync(int id)
        {
            await UserManager.DeleteUserById(_userManager, id);
            return Ok();
        }

        // [HttpPost]
        // [Route("DisableUsers")]
        // [Authorize(Roles = "Country Admin,Administrator")]
        // [ValidateAntiForgeryToken]
        // public async Task<IActionResult> DisableUsersAsync(DisableUsersRequest model)
        // {
        //     for (int i = 0; i < model.Emails.Count(); i++)
        //     {
        //         await UserManager.DisableUser(_userManager, _dataContext, model.Emails[i]);
        //     }
        //     return Ok();
        // }

        // [HttpPost]
        // [Authorize]
        // public JsonResult SetDefaultLanguage([FromBody] SetDefaultLanguageRequest request)
        // {
        //     BaseResponseViewModel viewModel = new BaseResponseViewModel();
        //     try
        //     {
        //         Models.Data.User.SetDefaultLanguage(_dataContext, request.UserId, request.LanguageId);
        //     }
        //     catch (Exception ex)
        //     {
        //         viewModel.Result = Models.Enums.ResultEnum.Error;
        //         viewModel.ErrorMessage = ex.Message;
        //     }
        //     return new JsonResult(viewModel);
        // }

        [HttpPost]
        [Route("ChangePassword")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePasswordAsync(ChangePasswordRequest model)
        {
            await UserManager.EditUserPassword(_userManager, model.UserId, model.OldPassword, model.NewPassword);
            return Ok();
        }
    }
}