using System;
using System.Text;
using System.IO;
using System.Linq;
using System.Globalization;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using SendGrid;
using SendGrid.Helpers.Mail;
using MongoDB.Bson;
using Metis.API.Models.Store;
using Metis.API.Models.Requests;
using Metis.API.Models.Managers;
using Metis.API.Models;

namespace Metis.API.Controllers
{
    [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme)]
    [ApiController]
    [Route("[controller]")]
    public class StudentController : BaseController
    {
        private readonly IConfiguration _configuration;
        private readonly RoleManager _roleManager;
        private readonly UserManager _userManager;
        private readonly AuthenticationManager _authenticationManager;

        public StudentController(ApplicationDbContext dataContext, IConfiguration configuration)
            : base(dataContext)
        {
            _configuration = configuration;
            _roleManager = new RoleManager(dataContext);
            _userManager = new UserManager(dataContext);

            var jwtOptions = new JwtOptions();
            _configuration.GetSection(nameof(JwtOptions)).Bind(jwtOptions); 
            _authenticationManager = new AuthenticationManager(jwtOptions, dataContext);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        [Route("AddStudent")]
        public async Task<IActionResult> AddStudentAsync(AddStudentRequest model)
        {
            int passwordlength = int.Parse(_configuration["Identity:AutoGeneratedPasswordLength"]);
            int numberOfNonAlphanumericCharacters = new Random().Next(1, passwordlength - 1);
            string password = Password.Generate(passwordlength, numberOfNonAlphanumericCharacters);

            Role role = await _roleManager.GetRoleByNameAsync("Student");
            await _userManager.AddUserAsync(model.FirstName, model.LastName, model.Email, model.Enabled, role.Id, model.LanguageId, password);

            var apiKey = _configuration["SendGrid:Key"];
            var client = new SendGridClient(apiKey);
            var msg = new SendGridMessage();
            msg.SetFrom(new EmailAddress("ivan.porta.web@gmail.com", "Ivan Porta"));
            msg.AddTo(new EmailAddress(model.Email, $"{model.FirstName} {model.LastName}"));
            msg.SetTemplateId("d-91d610861edb4a2cb48075c7f9c2b9fd");
            var dynamicTemplateData = new
            {
                FirstName = model.FirstName,
                Password = password
            };
            msg.SetTemplateData(dynamicTemplateData);
            await client.SendEmailAsync(msg);

            return Ok();
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        [Route("EditStudent")]
        public async Task<IActionResult> EditStudentAsync(EditStudentRequest model)
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            User user = await _userManager.GetUserByEmailAsync(model.Email);
            if (user == null)
            {
                return NotFound();
            }
            if (user.RoleId != role.Id)
            {
                return BadRequest();
            }
            await _userManager.EditUserAsync(model.Id, model.FirstName, model.LastName, model.Email, model.Enabled, model.LanguageId);
            return Ok();
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        [Route("GetStudents")]
        public async Task<IActionResult> GetStudentsAsync()
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            IEnumerable<User> users = await _userManager.GetUsersAsync(role.Id);
            return Ok(users);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme)]
        [Route("GetStudentById")]
        public async Task<IActionResult> GetStudentByIdAsync(int id)
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            User user = await _userManager.GetUserByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            if (user.RoleId != role.Id)
            {
                return BadRequest();
            }
            return Ok(user);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        [Route("GetStudentsByPage")]
        public async Task<IActionResult> GetStudentsByPageAsync(int page, int itemsPerPage)
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            IEnumerable<User> users = await _userManager.GetUsersByPageAsync(role.Id, page, itemsPerPage);
            return Ok(users);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        [Route("GetStudentsByPageAndSearchQuery")]
        public async Task<IActionResult> GetStudentsByPageAndSearchQueryAsync(int page, int itemsPerPage, string searchQuery)
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            IEnumerable<User> users = await _userManager.GetUsersByPageAsync(role.Id, page, itemsPerPage, searchQuery);
            return Ok(users);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        [Route("GetStudentsCount")]
        public async Task<IActionResult> GetStudentsCountAsync()
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            int counter = await _userManager.GetUsersCountAsync(role.Id);
            return Ok(counter);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        [Route("GetActiveStudentsCount")]
        public async Task<IActionResult> GetActiveStudentsCountAsync()
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            int counter = await _userManager.GetActiveUsersCountAsync(role.Id);
            return Ok(counter);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        [Route("GetStudentsBySearchQueryCount")]
        public async Task<IActionResult> GetStudentsBySearchQueryCountAsync(string searchQuery)
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            int counter = await _userManager.GetUsersCountAsync(role.Id, searchQuery);
            return Ok(counter);
        }

        [HttpDelete]
        [Route("DeleteStudentById")]
        [Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme, Roles = "Administrator, Teacher")]
        public async Task<IActionResult> DeleteStudentByIdAsync(int id)
        {
            Role role = await _roleManager.GetRoleByNameAsync("Student");
            User user = await _userManager.GetUserByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            if (user.RoleId != role.Id)
            {
                return BadRequest();
            }
            await _userManager.DeleteUserByIdAsync(id);
            return Ok();
        }
    }
}
